### PR TITLE
Update config.yaml

### PR DESCRIPTION
**Pull request by RosaWagner**

### CODE REVIEW

**Comment by coreyhu** [comment]
I ended up using this as a second config that exports the separated Roman and Italic versions to `./fonts/gfvariable` . A VF with both `wght` + `ital` axes can still be built to `./fonts/variable`.

**Comment by RosaWagner** [comment]
If you want to check out another method, my colleague use VarLib Instancer to split the VF. I didn’t have time to implement it in my workflow yet, so don’t know exactly how it works.

**Comment by coreyhu** [comment]
Thanks, I looked into VarLib Instancer and added it to the latest version to avoid maintaining multiple sourcefiles and configs

**Comment by RosaWagner** [comment]
That's awesome :) could then also add a bash script which executes the builder + varlib instancer so a user can replicate the build easily ?

**Pull request merged**
